export const userMessages = {
  VALIDATION_ERROR: "Validation error",
  NAME_IS_REQUIRED: "Name is required",
  NAME_MUST_BE_A_STRING: "Name must be a string",
  NAME_LENGTH: "Name length must be from 1 to 100",
  EMAIL_ALREADY_EXISTS: "Email already exists",
  EMAIL_IS_REQUIRED: "Email is required",
  EMAIL_IS_INVALID: "Email is invalid",
  PASSWORD_IS_REQUIRED: "Password is required",
  PASSWORD_MUST_BE_A_STRING: "Password must be a string",
  PASSWORD_LENGTH: "Password length must be from 6 to 50",
  PASSWORD_STRONG: "Password must be 6-50 characters long and contain at least 1 lowercase letter, 1 uppercase letter, 1 number and 1 symbol",
  CONFIRM_PASSWORD_IS_REQUIRED: "Confirm Password is required",
  CONFIRM_PASSWORD_MUST_BE_A_STRING: "Confirm Password must be a string",
  CONFIRM_PASSWORD_LENGTH: "Confirm Password length must be from 6 to 50",
  CONFIRM_PASSWORD_STRONG: "Confirm Password must be 6-50 characters long and contain at least 1 lowercase letter, 1 uppercase letter, 1 number and 1 symbol",
} as const
